services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://host.docker.internal:1433;databaseName=NewspaperAppDB;encrypt=false;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=L@mkhoa123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge